# Day 1 of Numpy

# Importing Numpy Library

In [1]:
import numpy as np

# Array DataTypes

In [4]:
a = np.array([1,2,3])
print(f"Array a using List: {a}")
print(f"Array a DTypes: {a.dtype}")
print('-' * 70)
b = np.array((1.,2.,3.))
print(f"Array b using Tuple: {b}")
print(f"Array b DTypes: {b.dtype}")
print('-' * 70)
c = np.array({7,'z',7.77,7+7j})
print(f"Array c using mix Datatypes: {c}")
print(f"Array c DTypes: {c.dtype}")

Array a using List: [1 2 3]
Array a DTypes: int64
----------------------------------------------------------------------
Array b using Tuple: [1. 2. 3.]
Array b DTypes: float64
----------------------------------------------------------------------
Array c using mix Datatypes: {(7+7j), 7, 'z', 7.77}
Array c DTypes: object


# Indexing and Slicing
# 1D Array

In [34]:
nparray = [x for x in range(1, 11, 1)]
print(f"Array nparray: {nparray}")
print(f"Accessing second element in array: {nparray[1]}")
print(f"Accessing last element in array: {nparray[-1]}")
print(f"Accessing element between 4 to 8: {nparray[3:8]}")
print(f"Reversed array: {nparray[::-1]}")
print(f"Accessing alternate elements: {nparray[::2]}")

Array nparray: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Accessing second element in array: 2
Accessing last element in array: 10
Accessing element between 4 to 8: [4, 5, 6, 7, 8]
Reversed array: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Accessing alternate elements: [1, 3, 5, 7, 9]


# 2D Array

In [11]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(f"Accessing element at index 2: {a[0][2]}")
print(f"Accessing second last element: {a[-1][-2]}")
print("Element at row 2, col 3:", a[1, 2])
print("First row:", a[0])
print("Third column:", a[:, 2])
print("Submatrix:\n", a[0:2, 2:])

Accessing element at index 2: 3
Accessing second last element: 7
Element at row 2, col 3: 7
First row: [1 2 3 4]
Third column: [3 7]
Submatrix:
 [[3 4]
 [7 8]]


# Array attributes: shape, size, ndim, dtype, itemsize

In [22]:
print('-' * 100)
a = np.array([1, 2, 3])
dim_a, shape_a, size_a, type_a = a.ndim, a.shape, a.size, a.dtype
print(f"Array a: \n{a} has {dim_a} dimension, shape {shape_a}, size {size_a} and datatype {type_a}")
print('-' * 100)

b = np.array([[1.,2,3,4],[5,6,7.,8.]])
dim_b, shape_b, size_b, type_b = b.ndim, b.shape, b.size, b.dtype
print(f"Array b: \n{b} has {dim_b} dimension, shape {shape_b} and size {size_b} and datatype {type_b}")
print('-' * 100)

c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
dim_c, shape_c, size_c, type_c = c.ndim, c.shape, c.size, c.dtype
print(f"Array c: \n{c} has {dim_c} dimension, shape {shape_c} and size {size_c} and datatype {type_c}")
print('-' * 100)

----------------------------------------------------------------------------------------------------
Array a: 
[1 2 3] has 1 dimension, shape (3,), size 3 and datatype int64
----------------------------------------------------------------------------------------------------
Array b: 
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] has 2 dimension, shape (2, 4) and size 8 and datatype float64
----------------------------------------------------------------------------------------------------
Array c: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]] has 3 dimension, shape (1, 3, 4) and size 12 and datatype int64
----------------------------------------------------------------------------------------------------


In [29]:
itemsize_a, itemsize_b, itemsize_c  = a.itemsize, b.itemsize, c.itemsize
print('-' * 100)
print(f"Itemsize of array a: {itemsize_a}")
print(f"Size of array a: {size_a}")
print(f"Total Memory used by a: {itemsize_a * size_a}")
print(f"Checking total bytes using nbyte function for a: {a.nbytes}")
if a.nbytes == itemsize_a * size_a:
    print("True")
print('-' * 100)
print(f"Itemsize of array b: {itemsize_b}")
print(f"Size of array b: {size_b}")
print(f"Total Memory used by b: {itemsize_b * size_b}")
print(f"Checking total bytes using nbyte function for b: {b.nbytes}")
if b.nbytes == itemsize_b * size_b:
    print("True")
print('-' * 100)
print(f"Itemsize of array c: {itemsize_c}")
print(f"Size of array c: {size_c}")
print(f"Total Memory used by c: {itemsize_c * size_c}")
print(f"Checking total bytes using nbyte function for c: {c.nbytes}")
if c.nbytes == itemsize_c * size_c:
    print("True")
print('-' * 100)

----------------------------------------------------------------------------------------------------
Itemsize of array a: 8
Size of array a: 3
Total Memory used by a: 24
Checking total bytes using nbyte function for a: 24
True
----------------------------------------------------------------------------------------------------
Itemsize of array b: 8
Size of array b: 8
Total Memory used by b: 64
Checking total bytes using nbyte function for b: 64
True
----------------------------------------------------------------------------------------------------
Itemsize of array c: 8
Size of array c: 12
Total Memory used by c: 96
Checking total bytes using nbyte function for c: 96
True
----------------------------------------------------------------------------------------------------


# Array Types:
1. arange() – Array with evenly spaced values (like range)
2. linspace() – Array with fixed number of values between a range
3. zeros() – All zeros
4. ones() - All ones
5. full() – All same value
6. eye() – Identity matrix
7. random – Random values

In [76]:
a = np.arange(2, 10)
print(f"Array a (arange): {a}")
b = np.arange(1, 4)
print(f"Array b (arange): {b+2}")
print('-' * 100)
c = np.linspace(0, 1, 5)
print(f"Array c (linspace): {c}")
print('-' * 100)
d = np.zeros((2, 3))
print(f"Array d (zeros): \n{d}")
print('-' * 100)
e = np.ones((3, 2))
print(f"Array e (ones): \n{e}")
print('-' * 100)
n = 7
f = np.full((n, n), n)
print(f"Array f (full): \n{f}")
print('-' * 100)
g = np.eye(5)
print(f"Array g (eye): \n{g}")
print('-' * 100)
h = np.random.rand(3, 5)
print(f"Array h (random.rand values between 0(inclusive) and 1(exclusive)): \n{h}\n")
i = np.random.rand(3)
print(f"Array i (random.rand values between 0(inclusive) and 1(exclusive)): \n{i}")
print('-' * 100)
j = np.random.randint(1, 11, (2,3))
print(f"Array j (random integer values between given range and dimension): \n{j}")

Array a (arange): [2 3 4 5 6 7 8 9]
Array b (arange): [3 4 5]
----------------------------------------------------------------------------------------------------
Array c (linspace): [0.   0.25 0.5  0.75 1.  ]
----------------------------------------------------------------------------------------------------
Array d (zeros): 
[[0. 0. 0.]
 [0. 0. 0.]]
----------------------------------------------------------------------------------------------------
Array e (ones): 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
----------------------------------------------------------------------------------------------------
Array f (full): 
[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
----------------------------------------------------------------------------------------------------
Array g (eye): 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------------------------------------------------------

# Broadcasting

In [92]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = 10/2
print(a+b)
print(c**a)

[11 12 13 14 15]
[   5.   25.  125.  625. 3125.]


In [93]:
a = np.arange(1,14,4)
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a * b)

[[  1  10  27  52]
 [  5  30  63 104]]


In [96]:
a = np.array([[1], [2], [3]])
b = np.array([1,2,3])
print("-" * 100)
print(f"Addition: \n{a + b}")
print("-" * 100)
print(f"Substraction: \n{a - b}")
print("-" * 100)
print(f"Multiplication: \n{a * b}")
print("-" * 100)
print(f"Division: \n{a / b}")
print("-" * 100)
print(f"Integer Division: \n{a // b}")
print("-" * 100)

----------------------------------------------------------------------------------------------------
Addition: 
[[2 3 4]
 [3 4 5]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
Substraction: 
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
----------------------------------------------------------------------------------------------------
Multiplication: 
[[1 2 3]
 [2 4 6]
 [3 6 9]]
----------------------------------------------------------------------------------------------------
Division: 
[[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]
----------------------------------------------------------------------------------------------------
Integer Division: 
[[1 0 0]
 [2 1 0]
 [3 1 1]]
----------------------------------------------------------------------------------------------------


# Reshape Array

In [105]:
a = np.array([x for x in range(8)])
b = a.reshape(2,4)
c = a.reshape((2,2,2))
transpose = a.reshape(4,-1)
print("Original Array: \n", a)
print('-' *50)
print("Reshaped 2D Array: \n", b)
print('-' *50)
print("Reshaped 3D Array: \n", c)
print('-' *50)
print("Reshaped Transpose Array: \n", transpose)

Original Array: 
 [0 1 2 3 4 5 6 7]
--------------------------------------------------
Reshaped 2D Array: 
 [[0 1 2 3]
 [4 5 6 7]]
--------------------------------------------------
Reshaped 3D Array: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
--------------------------------------------------
Reshaped Transpose Array: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Flatten Array

In [110]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
b = a.flatten()
print("Original array:\n", a)
print('-' * 100)
print("Flattened array:", b)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------------------------------------------------------------------------------
Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


# Ravel Array

In [113]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = a.ravel()
print("Original array:\n", a)
print("Ravelled array:", b)
b[1] += 5
print("Modified original:\n", a)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ravelled array: [1 2 3 4 5 6 7 8 9]
Modified original:
 [[1 7 3]
 [4 5 6]
 [7 8 9]]


# Stacking and Splitting
1. hstack()
2. vstack()
3. concatenate()
4. split()
5. array_split()
6. hsplit()
7. vsplit()

In [121]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
print("Horizontal Stack: ", c)
print('-' * 50)
a = np.array([[1], [2]])
b = np.array([[3], [4]])
c = np.hstack((a,b))
print("Horizontal Stack 2D: \n", c)
print('-' * 50)
print('-' * 50)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.vstack((a,b,c))
print("Vertical Stack: \n", d)
print('-' * 50)
a = np.array([[1], [2]])
b = np.array([[3], [4]])
c = np.vstack((a,b))
print("Vertical Stack 2D: \n", c)
print('-' * 50)
print('-' * 50)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
print("Concatenated along rows:\n", c)
print('-' * 50)
d = np.concatenate((a, b.T), axis=1)
print("Concatenated along columns:\n", d)


Horizontal Stack:  [1 2 3 4 5 6]
--------------------------------------------------
Horizontal Stack 2D: 
 [[1 3]
 [2 4]]
--------------------------------------------------
--------------------------------------------------
Vertical Stack: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
Vertical Stack 2D: 
 [[1]
 [2]
 [3]
 [4]]
--------------------------------------------------
--------------------------------------------------
Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
Concatenated along columns:
 [[1 2 5]
 [3 4 6]]


In [129]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.split(a,5)
print("Split Even: ", b)
print('-' * 120)
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.array_split(c,7)
print("Split Uneven: ", d)
print('-' * 120)

Split Even:  [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
------------------------------------------------------------------------------------------------------------------------
Split Uneven:  [array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8]), array([9]), array([10])]
------------------------------------------------------------------------------------------------------------------------


In [130]:
a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print("Original 2D array a: \n", a)
print('-' * 80)
col_split = np.hsplit(a, 3)
print("Column-wise split:\n", col_split)
print('-' * 80)
row_split = np.vsplit(a, 3)
print("Row-wise split:", row_split)
print('-' * 80)

Original 2D array a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------------------------------------
Column-wise split:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
--------------------------------------------------------------------------------
Row-wise split: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
--------------------------------------------------------------------------------


# Element-wise operations
1. Add
2. Subtract
3. Multiply
4. Divide

In [133]:
a = np.array([1,2,3,4,5])
b = np.array((6,7,8,9,10))
add = np.add(a, b) # a + b
sub = np.subtract(a, b) # a - b
mul = np.multiply(a, b) # a * b
div = np.divide(a, b) # a / b
print(f"Addition: {add}")
print(f"Substraction: {sub}")
print(f"Multiplication: {mul}")
print(f"Division: {div}")

Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Aggregate functions:
1. Sum
2. Product
3. Mean
4. Median
5. Std
6. Variance
7. Min
8. Max
9. Argmin
10. Argmax
11. CumSum

In [157]:
# prod
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(f"Sum of array a: {np.sum(a)}")
print(f"Product of array a: {np.prod(a)}")
print(f"Mean of array a: {np.mean(a)}")
print(f"Median of array a: {np.median(a)}")
print(f"Standard Deviation of array a: {np.std(a)}")
print(f"Variance of array a: {np.var(a)}")
print(f"Minimum of array a: {np.min(a)}")
print(f"Maximum of array a: {np.max(a)}")
print(f"Index of minimum of array a: {np.argmin(a)}")
print(f"Index of maximum of array a: {np.argmax(a)}")
print(f"Cumulative sum of array a: {np.cumsum(a)}")


Sum of array a: 120
Product of array a: 1307674368000
Mean of array a: 8.0
Median of array a: 8.0
Standard Deviation of array a: 4.320493798938574
Variance of array a: 18.666666666666668
Minimum of array a: 1
Maximum of array a: 15
Index of minimum of array a: 0
Index of maximum of array a: 14
Cumulative sum of array a: [  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]


# Mathematical functions
1. np.sqrt
2. np.exp
3. np.log

In [151]:
a = [x for x in range(1, 11)]
print(f"Square Roots of Array a: {np.sqrt(a)}")
print('-' * 100)
print(f"Exp of Array a: {np.exp(a)}")
print('-' * 100)
print(f"Log of Array a: {np.log(a)}")

Square Roots of Array a: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
----------------------------------------------------------------------------------------------------
Exp of Array a: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
----------------------------------------------------------------------------------------------------
Log of Array a: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


1. Create a NumPy array from a list and print its dtype, ndim, shape, size and itemsize - Easy

In [158]:
a = np.array([1,2,3,4,5])
print(f"Array a: {a}")
print(f"Array a dtype: {a.dtype}")
print(f"Array a ndim: {a.ndim}")
print(f"Array a shape: {a.shape}")
print(f"Array a size: {a.size}")
print(f"Array a itemsize: {a.itemsize}")

Array a: [1 2 3 4 5]
Array a dtype: int64
Array a ndim: 1
Array a shape: (5,)
Array a size: 5
Array a itemsize: 8


2. Generate an array with arange() from 10 to 30 and slice out every 3rd element. - Easy

In [159]:
a = np.arange(10, 31, 3)
print(f"Array a: {a}")

Array a: [10 13 16 19 22 25 28]


3. Create a 3x3 identity matrix using eye() and multiply by 5 element-wise. - Easy

In [160]:
a = np.eye(3)
b = a * 5
print(f"Array a: \n{a}")
print(f"Array b: \n{b}")

Array a: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array b: 
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


4. Extract rows 1 to 3 and columns 0 to 2 from a 5x5 random integer matrix. - Medium

In [166]:
a = np.random.randint(0, 11, (5, 5))
print(f"Array a: \n{a}")
print(f"Extract rows 1 to 3: {a[1:4]}")
print(f"Extract columns 0 to 2: {a[:, 0:2]}")

Array a: 
[[ 2  3 10  5  1]
 [ 8  0  7  6 10]
 [10  1  5  6  9]
 [ 0  0  6  5 10]
 [ 1  6  7  2  4]]
Extract rows 1 to 3: [[ 8  0  7  6 10]
 [10  1  5  6  9]
 [ 0  0  6  5 10]]
Extract columns 0 to 2: [[ 2  3]
 [ 8  0]
 [10  1]
 [ 0  0]
 [ 1  6]]


5. Reshape a 1D array of 16 elements to 4x4 and then flatten it back to 1D with ravel(). - Medium

In [175]:
a = np.arange(0, 16)
b = np.reshape(a, (4,4))
c = np.ravel(b)
d = b.flatten()
print(f"Original Array: {a}")
print(f"Reshaped Array: \n{b}")
print(f"Ravelled Array: {c}")
print(f"Flattened Array: {d}")

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Ravelled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


6. Use linspace() to create an array of 50 points between 0 and 5 inclusive, then compute its cumulative sum.

In [177]:
a = np.linspace(0, 5, 50)
print(f"Array a: {a}")
cum_sum = np.cumsum(a)
print(f"Cumulative Sum: {cum_sum}")

Array a: [0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
Cumulative Sum: [0.00000000e+00 1.02040816e-01 3.06122449e-01 6.12244898e-01
 1.02040816e+00 1.53061224e+00 2.14285714e+00 2.85714286e+00
 3.67346939e+00 4.59183673e+00 5.61224490e+00 6.73469388e+00
 7.95918367e+00 9.28571429e+00 1.07142857e+01 1.22448980e+01
 1.38775510e+01 1.56122449e+01 1.74489796e+01 1.93877551e+01
 2.14285714e+01 2.35714286e+01 2.58163265e+01 2.81632653e+01
 3.06122449e+01 3.31632653e+01 3.58163265e+01 3.8

7. Concatenate two arrays horizontally and then split the result into 3 equal parts vertically.


In [183]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b), axis=0)
c_2d = c.reshape(3, 2)
d = np.vsplit(c_2d, 3)
print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Concatenated Array: {c}")
print("Splitted Array:")
for part in d:
    print(part)

Array a: [1 2 3]
Array b: [4 5 6]
Concatenated Array: [1 2 3 4 5 6]
Splitted Array:
[[1 2]]
[[3 4]]
[[5 6]]


8. Create two arrays of different shapes and perform broadcasting in addition and multiplication.


In [189]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.arange(4, 8)
print(f"Array a: \n{a}")
print(f"Array b: {b}")
c = np.add(a, b)
d = np.multiply(a, b)
print(f"Addition: \n{c}")
print(f"Multiplication: \n{d}")

Array a: 
[[1 2 3 4]
 [5 6 7 8]]
Array b: [4 5 6 7]
Addition: 
[[ 5  7  9 11]
 [ 9 11 13 15]]
Multiplication: 
[[ 4 10 18 28]
 [20 30 42 56]]


9. Find the indices of minimum and maximum of a 2D random float array, then compute row-wise mean and std deviation.


In [199]:
a = np.random.rand(3, 3)
print(f"Array a: \n{a}")
print(f"Index of Minimum: {np.argmin(a)}")
print(f"Index of Maximum: {np.argmax(a)}")
print(f"Row-wise Mean: {np.mean(a, axis=1)}")
print(f"Row-wise Standard Deviation: {np.std(a, axis=1)}")

Array a: 
[[0.64060725 0.30257525 0.15698383]
 [0.49792891 0.92507672 0.81032876]
 [0.27032027 0.83518877 0.55572347]]
Index of Minimum: 2
Index of Maximum: 4
Row-wise Mean: [0.36672211 0.7444448  0.55374417]
Row-wise Standard Deviation: [0.2025817  0.18049808 0.23061084]


10. Generate a 3D array and reverse it along the second axis (axis=1).


In [207]:
a = np.random.randint(0, 11, (3,3))
b = np.flip(a, axis=1)
c = np.flip(a, axis=0)
print(f"Array a: \n{a}")
print(f"Reversed Array: \n{b}")
print(f"Reversed Array: \n{c}")

Array a: 
[[2 9 5]
 [5 7 7]
 [4 1 9]]
Reversed Array: 
[[5 9 2]
 [7 7 5]
 [9 1 4]]
Reversed Array: 
[[4 1 9]
 [5 7 7]
 [2 9 5]]


11. Create a full() array with shape (4,5) filled with 7, and update a submatrix to zeros using slicing.


In [212]:
a = np.full((4,5), 7)
print(f"Original Array a: \n{a}")
a[0:2, 1:3] = 0
a[2:4, 2:4] = 0
print(f"Modified Array a: \n{a}")

Original Array a: 
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Modified Array a: 
[[7 0 0 7 7]
 [7 0 0 7 7]
 [7 7 0 0 7]
 [7 7 0 0 7]]


12. Use random.randint() to generate a 10x10 matrix simulating dice rolls, then compute product of all elements.


In [228]:
import math
a = np.random.randint(1, 7, (10, 10))
print(f"Array a: \n{a}")
prod = math.prod(a)
print(f"Product of all elements: {prod}")

Array a: 
[[2 5 2 4 4 1 1 3 4 4]
 [5 1 6 2 5 1 3 1 5 1]
 [3 2 4 2 2 5 4 1 1 6]
 [2 4 5 5 3 1 3 5 2 4]
 [1 1 5 4 4 4 4 4 1 1]
 [6 3 1 1 5 4 4 1 4 2]
 [3 6 4 1 1 3 2 2 5 6]
 [3 4 6 2 5 3 6 4 4 2]
 [6 6 3 6 5 6 4 6 6 2]
 [2 5 6 4 1 3 4 4 2 6]]
Product of all elements: [ 38880  86400 518400  15360  60000  12960 110592  11520  38400  27648]


13. Create two arrays and demonstrate difference between flatten() and ravel() by modifying returned arrays.


In [230]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
b = a.flatten()
print("Original array:\n", a)
print('-' * 100)
print("Flattened array:", b)
print('-' * 100)
print('-' * 100)
b = a.ravel()
print("Original array:\n", a)
print("Ravelled array:", b)
b[1] += 5
print("Modified original:\n", a)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------------------------------------------------------------------------------
Flattened array: [ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Ravelled array: [ 1  2  3  4  5  6  7  8  9 10]
Modified original:
 [[ 1  7  3  4  5]
 [ 6  7  8  9 10]]


14. Compute logarithm, exponential, and square root for an array of values using np.log(), np.exp(), np.sqrt().




In [238]:
a = np.random.randint(1, 21, 5)
print(f"Square Roots of Array a: {np.log(a)}")
print('-' * 100)
print(f"Exponential of Array a: {np.exp(a)}")
print('-' * 100)
print(f"Log of Array a: {np.sqrt(a)}")

Square Roots of Array a: [1.38629436 2.63905733 2.7080502  1.09861229 2.89037176]
----------------------------------------------------------------------------------------------------
Exponential of Array a: [5.45981500e+01 1.20260428e+06 3.26901737e+06 2.00855369e+01
 6.56599691e+07]
----------------------------------------------------------------------------------------------------
Log of Array a: [2.         3.74165739 3.87298335 1.73205081 4.24264069]


# Day 2 of Numpy

# Logical Operation & Masking

In [32]:
import numpy as np

a = np.random.randint(1, 21, 10)
print(f"Array a: {a}")
print(f"Greater than 10: {a[a > 10]}")
print(f"Less than 10: {a[a < 10]}")
print(f"Equal to 10: {a[a == 10]}")
print(f"Not Equal to 10: {a[a != 10]}")
print(f"Greater than or equal to 10: {a[a >= 10]}")
print(f"Less than or equal to 10: {a[a <= 10]}")

print(f"Greater than 2 and less than 8: {a[(a > 2) & (a < 8)]}")
print(f"Not greater than 10: {a[~(a > 10)]}")

Array a: [ 1  1 15 11 11 10 10 15 15 14]
Greater than 10: [15 11 11 15 15 14]
Less than 10: [1 1]
Equal to 10: [10 10]
Not Equal to 10: [ 1  1 15 11 11 15 15 14]
Greater than or equal to 10: [15 11 11 10 10 15 15 14]
Less than or equal to 10: [ 1  1 10 10]
Greater than 2 and less than 8: []
Not greater than 10: [ 1  1 10 10]


In [38]:
mask = a >= 12
print("Greater than 12:", mask)

filter_value = a[mask]
print("Filtered values:", filter_value)

Greater than 12: [False False  True False False False False  True  True  True]
Filtered values: [15 15 15 14]


In [44]:
b = np.array([x for x in np.random.randint(1, 101, 20)])
print(f"Array b: {b}")

mask = (b % 2 == 0)
print(f"Even Numbers: {np.sort(b[mask])}")
print(f"Odd Numbers: {np.sort(b[~mask])}")

Array b: [19 96 77 34 55 56 19  4 14 81 50 28 60 83 62 47 42 85 54 67]
Even Numbers: [ 4 14 28 34 42 50 54 56 60 62 96]
Odd Numbers: [19 19 47 55 67 77 81 83 85]


In [46]:
result = np.where(b > 50, ">50", "<50")
result = np.where(b == 50, "=50", result)
print(f"Array b: {b}")
print(f"Result: {result}")

Array b: [19 96 77 34 55 56 19  4 14 81 50 28 60 83 62 47 42 85 54 67]
Result: ['<50' '>50' '>50' '<50' '>50' '>50' '<50' '<50' '<50' '>50' '=50' '<50'
 '>50' '>50' '>50' '<50' '<50' '>50' '>50' '>50']


In [53]:
g = l = e = 0

for i in b:
  if i > 50:
    g += 1
  elif i < 50:
    l += 1
  else:
    e += 1

print(f"Array b: {b}")
print(f"Greater than 50: {g}")
print(f"Less than 50: {l}")
print(f"Equal to 50: {e}")

Array b: [19 96 77 34 55 56 19  4 14 81 50 28 60 83 62 47 42 85 54 67]
Greater than 50: 11
Less than 50: 8
Equal to 50: 1


In [55]:
indices = np.where(b > 70)
print("Indices where elements are greater than 70:", indices)

values_greater_than_70 = b[np.where(b > 70)]
print("Values greater than 7:", np.sort(values_greater_than_70))

Indices where elements are greater than 70: (array([ 1,  2,  9, 13, 17]),)
Values greater than 7: [77 81 83 85 96]


In [60]:
a = np.arange(-2,3)
condition = [a < 0, a == 0, a > 0]
choice = ["Negative", "Neutral", "Positive"]
result = np.select(condition, choice, default="Unknown")
print("Result:", result)

Result: ['Negative' 'Negative' 'Neutral' 'Positive' 'Positive']


# Fancy Indexing

In [64]:
a = np.array([10, 20, 30, 40, 50])
a[[0, 2, 3+1]]

array([10, 30, 50])

In [66]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
a[[2, 1, 0], [0, 1, 2]]

array([70, 50, 30])

In [68]:
a = np.random.randint(1, 51, (5, 5))
print(f"Array a: \n{a}")

Array a: 
[[31  5 31 12 30]
 [27 28  6 13  5]
 [ 5 24 43 46 21]
 [50 35 41 26 43]
 [16 49 26 30 16]]


In [75]:
print(a[[1,3,0,1], [1,2,4,4]])
print(a[0:2])
print(a[[0,2]])

[28 41 30  5]
[[31  5 31 12 30]
 [27 28  6 13  5]]
[[31  5 31 12 30]
 [ 5 24 43 46 21]]


# Shuffle & Random

In [85]:
a = np.random.randint(1, 11, 10)
print(f"Array a: {a}")
b = np.random.shuffle(a)
print(f"Shuffled Array a: {a}")
c = np.random.permutation(a)
print(f"Permutated Array a: {c}")
d = np.random.choice(a, size=3, replace=False)
print(f"Randomly Selected Element: {d}")

Array a: [ 5  3  2  2  3  4 10  4  7  7]
Shuffled Array a: [ 3  2  5  7  4  7  4  2 10  3]
Permutated Array a: [ 4 10  7  4  7  2  3  2  3  5]
Randomly Selected Element: [ 7 10  7]


# Advanced Indexing and Boolean Masking

In [93]:
a = np.array([0, 0, 1, 0])
print("np.any result:", np.any(a > 0))
print('-' * 50)

a = np.array([1, 2, 3])
print("np.all result:", np.all(a > 1))
print('-' * 50)

np.any result: True
--------------------------------------------------
np.all result: False
--------------------------------------------------


# Linear Algebra
- Vectors & Matrices
- Matrix Transpose
- Dot Product
- Matrix Multiplication
- Identity Matrix
- Inverse
- Determinant
- Eigenvalues & Vectors
- Norm
- Solving Linear Eq.

In [98]:
import numpy as np
from numpy import linalg as lg

vector = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3,4], [5,6,7,8]])

transpose_matrix = matrix.T

print("Vector:", vector)
print('-' * 50)
print("Matrix:\n", matrix)
print('-' * 50)
print("Transpose Matrix:\n", transpose_matrix)

Vector: [1 2 3 4 5]
--------------------------------------------------
Matrix:
 [[1 2 3 4]
 [5 6 7 8]]
--------------------------------------------------
Transpose Matrix:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [101]:
vector1 = np.array([1,2,3,4])
vector2 = np.array((5,6,7,8))
dot_product = np.dot(vector1, vector2)
print("Dot Product:", dot_product)
print('-' * 100)
matrix1 = np.array([[1,2,3], [4,5,6]])
matrix2 = np.array([[7,8], [9,10], [11,12]])
matrix_product = np.dot(matrix1, matrix2)
print("Matrix Product:\n", matrix_product)
print('-' * 100)

Dot Product: 70
----------------------------------------------------------------------------------------------------
Matrix Product:
 [[ 58  64]
 [139 154]]
----------------------------------------------------------------------------------------------------


In [103]:
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = lg.inv(matrix)
print("Inverse of Matrix:\n", inverse_matrix)
print('-' * 100)
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
determinant = lg.det(matrix)
print("Determinant:", determinant)
print('-' * 100)
eigenvalues, eigenvectors = lg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print('-' * 100)

Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
----------------------------------------------------------------------------------------------------
Determinant: 0.0
----------------------------------------------------------------------------------------------------
Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
----------------------------------------------------------------------------------------------------


In [104]:
norm = lg.norm(vector)
print("Norm:", norm)
print('-' * 100)
a = np.array([1,2,3,4,5])
norm = 0
for i in range(len(a)):
    new = a[i]**2
    norm = norm + new
norm = np.sqrt(norm)
print("Norm via coding:", norm)
print('-' * 100)
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("Solution to the system of equations:", x)
print('-' * 100)

Norm: 7.416198487095663
----------------------------------------------------------------------------------------------------
Norm via coding: 7.416198487095663
----------------------------------------------------------------------------------------------------
Solution to the system of equations: [2. 3.]
----------------------------------------------------------------------------------------------------


# Saving and Loading Array

In [107]:
np.save("arr.npy", a)

In [108]:
b = np.load("arr.npy")
b

array([1, 2, 3, 4, 5])

1. Create a boolean mask for an array to select elements greater than 10 and print the masked array.


In [118]:
a = np.random.randint(1, 21, 10)
mask = a > 10
print(f"Array a: {a}")
print(f"Masked Array: {a[mask]}")
print(f"Total number of elements greater than 10 is {len(a[mask])}")

Array a: [12 20  9 14 10  4 17  7 20  4]
Masked Array: [12 20 14 17 20]
Total number of elements greater than 10 is 5


2. Use np.select to categorize array elements into 'small' (<20), 'medium' (20-50), and 'large' (>50).


In [122]:
a = np.random.randint(1, 101, 10)
print(f"Array a: {a}")
condition = [a < 20, (a >= 20) & (a <= 50), a > 50]
choice = ["small", "medium", "large"]
result = np.select(condition, choice, default='unknown')
print(f"Result: {result}")
med = sma = lar = 0
for i in result:
  if i == "small":
    sma += 1
  elif i == "medium":
    med += 1
  else:
    lar += 1
print(f"Total number of elements in small category is {sma}")
print(f"Total number of elements in medium category is {med}")
print(f"Total number of elements in large category is {lar}")

Array a: [33 17 82 52 50 35 55 15 20 90]
Result: ['medium' 'small' 'large' 'large' 'medium' 'medium' 'large' 'small'
 'medium' 'large']
Total number of elements in small category is 2
Total number of elements in medium category is 4
Total number of elements in large category is 4


3. Shuffle an array of integers in place and print both original and shuffled arrays.


In [125]:
a = np.random.randint(1, 11, 10)
print(f"Array a: {a}")
b = np.random.shuffle(a)
print(f"Shuffled Array a: {a}")
c = np.sort(a)
print(f"Sorted Array a: {c}")

Array a: [1 3 2 5 8 1 9 1 2 1]
Shuffled Array a: [5 2 2 1 1 8 9 1 3 1]
Sorted Array a: [1 1 1 1 2 2 3 5 8 9]


4. Save a random array to disk using np.save, load it back, and verify if arrays are equal.


In [129]:
np.save("test.npy", a)
b = np.load("test.npy")
print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Are arrays equal? {np.array_equal(a, b)}")

Array a: [5 2 2 1 1 8 9 1 3 1]
Array b: [5 2 2 1 1 8 9 1 3 1]
Are arrays equal? True


5. Find the indices of all negative numbers in an integer array using np.where.


In [133]:
a = np.random.randint(-10, 11, 10)
print(f"Array a: {a}")
mask = a < 0
print(f"Indices of negative numbers: {np.where(mask)}")

Array a: [ -2   1  -7 -10  -9  -1   8  -9  -4   1]
Indices of negative numbers: (array([0, 2, 3, 4, 5, 7, 8]),)


6. Create a 2D array & extract all elements where the sum of r + c indices is odd using fancy indexing.


In [137]:
a = np.random.randint(1, 11, (5, 5))
print(f"Array a: \n{a}")
rows, cols = np.indices(a.shape)
print("Row indices:\n", rows)
print("Column indices:\n", cols)
mask = (rows + cols) % 2 != 0
print("Odd indices mask:\n", mask)

Array a: 
[[ 5  2  8  6  9]
 [10  7  8  7  3]
 [ 9  5  8 10  5]
 [ 8  5 10  1  8]
 [ 9 10  6  8  2]]
Row indices:
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
Column indices:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Odd indices mask:
 [[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


7. For a large array, count how many elements satisfy multiple conditions using loops and np.any / np.all.


In [150]:
a = np.random.randint(1, 101, (5,5))
print(f"Array a: {a}")
any_row = np.any(a > 50, axis=1)
all_row = np.all(a > 50, axis=1)
print("Any >50 per row:", any_row)
print("All >50 per row:", all_row)

Array a: [[72  9 96  8  6]
 [45 31 66  6 77]
 [55 57 92 65 83]
 [91 77 81  2 31]
 [51 36 31 19 51]]
Any >50 per row: [ True  True  True  True  True]
All >50 per row: [False False  True False False]


8. Perform matrix multiplication between two compatible matrices and compute the transpose of the result.


In [153]:
a = np.random.randint(1, 11, (3,3))
b = np.random.randint(1, 11, (3,3))
print(f"Array a: \n{a}")
print(f"Array b: \n{b}")
c = np.dot(a, b)
print(f"Matrix Multiplication: \n{c}")
print(f"Transpose of Matrix Multiplication: \n{c.T}")

Array a: 
[[ 5  9 10]
 [ 1  3  5]
 [ 8 10  7]]
Array b: 
[[10  5  2]
 [ 9  5  3]
 [ 7  7  2]]
Matrix Multiplication: 
[[201 140  57]
 [ 72  55  21]
 [219 139  60]]
Transpose of Matrix Multiplication: 
[[201  72 219]
 [140  55 139]
 [ 57  21  60]]


9. Calculate the determinant, inverse, and eigenvalues of a 3x3 matrix


In [154]:
a = np.random.randint(1, 11, (3,3))
print(f"Array a: \n{a}")
det = lg.det(a)
print(f"Determinant: {det}")
inv = lg.inv(a)
print(f"Inverse: \n{inv}")
eigenvalues, eigenvectors = lg.eig(a)
print(f"Eigenvalues: {eigenvalues}")

Array a: 
[[10  3  2]
 [ 3  8  9]
 [ 9 10  4]]
Determinant: -456.9999999999998
Inverse: 
[[ 0.12691466 -0.01750547 -0.02407002]
 [-0.15098468 -0.04814004  0.18380744]
 [ 0.09190372  0.15973742 -0.15536105]]
Eigenvalues: [18.85925337  6.73740425 -3.59665763]


10. Use np.where with multiple conditions to replace negative values with 0, values between 0-10 with 1, else 2.


In [156]:
a = np.random.randint(-10, 21, 10)
print(f"Array a: {a}")
mask = np.where(a < 0, 0, np.where((a >= 0) & (a <= 10), 1, 2))
print(f"Result: {mask}")

Array a: [ 9 13 18  0  9 -3 -7 13 14 -1]
Result: [1 2 2 1 1 0 0 2 2 0]


11. Randomly select 5 unique elements from a large array using np.random.choice.


In [159]:
a = np.random.randint(1, 11, 100)
print(f"Array a: {a}")
b = np.random.choice(a, size=5, replace=False)
print(f"Randomly Selected Elements: {b}")

Array a: [ 3  9  7  8  5  6  4  7  5  3  4  6  5  9  7  1  8  9  4  5  4  5  4  1
  5 10  3  5  7  7  3  5  6  3  9  8  9  9  3  8  9  8  7  7 10 10  1  4
 10  8  2  2  6  3 10 10  5  9  1  8  4  5  9  9  6  5  9  3  8  4  6  5
  3 10  5  7  2  2  5  9  9  5  8  2  5  5  8  7  3  2 10  8  4  2  4 10
  5  3  7  1]
Randomly Selected Elements: [ 7  1 10  9  5]
